name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-package:
    runs-on: ${{ '{{' }} matrix.os {{ '}}' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ '{{' }} matrix.python-version {{ '}}' }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ '{{' }} matrix.python-version {{ '}}' }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython --install-option='--no-cython-compile'
      - name: Install
        run: |
          pip install -r requirements-dev.txt
      - name: Lint with flake8
        run: |
          invoke lint
      - name: Test import
        run: |
          python -m {{cookiecutter.project_slug}}
      - name: Test with pytest
        run: |
          invoke test

